=== BootsOnTheGround-3Caretakers/batch_match/schemas/user.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "userId": {
            "type": "integer"
        },
        "role": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "screenname": {
            "type": "string"
        },
        "email": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "isVerified": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false,
            "required": [
                "address",
                "isVerified"
            ]
        },
        "phone": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "string"
                },
                "isVerified": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false,
            "required": [
                "number",
                "isVerified"
            ]
        },
        "address": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "type": "string"
                },
                "regionCode": {
                    "type": "string"
                },
                "languageCode": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "locality": {
                    "type": "string"
                },
                "addressApproximate": {
                    "type": "string"
                },
                "geo": {
                    "type": "object",
                    "properties": {
                        "lat": {
                            "type": "number"
                        },
                        "lon": {
                            "type": "number"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "lat",
                        "lon"
                    ]
                }
            },
            "additionalProperties": false,
            "required": [
                "countryCode",
                "regionCode",
                "languageCode",
                "postalCode",
                "locality",
                "addressApproximate",
                "geo"
            ]
        },
        "biography": {
            "type": "string"
        },
        "freeNotes": {
            "type": "string"
        },
        "imageUrls": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "additionalItems": false
        },
        "otherUrls": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "additionalItems": false
        },
        "criticalCategories": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "additionalItems": false
        },
        "hashtags": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "isVerified": {
                            "type": "boolean"
                        },
                        "isRequired": {
                            "type": "boolean"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "name",
                        "isVerified",
                        "isRequired"
                    ]
                }
            ],
            "additionalItems": false
        },
        "giveOffers": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "totalSlots": {
                            "type": "integer"
                        },
                        "availableSlots": {
                            "type": "integer"
                        },
                        "assignedSlots": {
                            "type": "integer"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "name",
                        "totalSlots",
                        "availableSlots",
                        "assignedSlots"
                    ]
                }
            ],
            "additionalItems": false
        },
        "isFirstResponder": {
            "type": "boolean"
        },
        "stillHaveToPhysicallyGoToWork": {
            "type": "boolean"
        },
        "redFlag": {
            "type": "boolean"
        },
        "lastUpdated": {
            "type": "string"
        },
        "createdAt": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": [
        "userId",
        "role",
        "name",
        "screenname",
        "email",
        "phone",
        "address",
        "biography",
        "freeNotes",
        "imageUrls",
        "otherUrls",
        "criticalCategories",
        "hashtags",
        "giveOffers",
        "isFirstResponder",
        "stillHaveToPhysicallyGoToWork",
        "redFlag",
        "lastUpdated",
        "createdAt"
    ]
}

=== BootsOnTheGround-3Caretakers/batch_match/schemas/user_sample.json
{
    "userId": 100,
    "role": "giver",
    "name": "Joe Smith",
    "screenname": "joesmith",
    "email": {
        "address": "joesmith@gmail.com",
        "isVerified": true
    },
    "phone": {
        "number": "(406) 555-1212",
        "isVerified": true
    },
    "address": {
        "countryCode": "US",
        "regionCode": "OR",
        "languageCode": "en",
        "postalCode": "97219",
        "locality": "Portland",
        "addressApproximate": "123 SE Street Ave.",
        "geo": {
            "lat": 29.1300,
            "lon": -71.000
        }
    },
    "biography": "I am a good person.",
    "freeNotes": "This person is a good person.",
    "imageUrls": ["https://foo.com/foo.jpg"],
    "otherUrls": ["https://foo.com/"],
    "criticalCategories": ["medicalWorker"],
    "hashtags": [
        {
            "name": "over70",
            "isVerified": true,
            "isRequired": true
        }
    ],
    "giveOffers": [
        {
            "name": "groceryDelivery",
            "totalSlots": 10,
            "availableSlots": 0,
            "assignedSlots": 10
        }
    ],
    "isFirstResponder": true,
    "stillHaveToPhysicallyGoToWork": true,
    "redFlag": false,
    "lastUpdated": "2019-01-20 HH:mm:ss",
    "createdAt": "2019-01-20 HH:mm:ss"
}
